/* 
 * This is an auto-generated file based on the 
 * configuration of the XBee Programmable project.
 * 
 * Do not edit this file.
 */

#ifndef __XBEE_CONFIG_H_
#define __XBEE_CONFIG_H_

/* Project definitions */
#define APP_VERSION_STRING              "water_sensor"
#define CONFIG_XBEE_ZB
#define CONFIG_XBEE_THT
#define CONFIG_XBEE_S2CTH
#define CONFIG_XBEE_FLASH_LEN           32

/* system0 component */
#define SYS_CFG_CLK_48_MHz
#define SYS_CFG_BUSCLK_SYSCLK_DIV2
#define ENABLE_WD
#define WD_CFG_LONG_TOUT

/* special0 component */
#define ENABLE_ASSOCIATION_LED_XPIN_15
#define ENABLE_COMMISSIONING_XPIN_20
#define ENABLE_RESET_PIN_XPIN_5
#define ENABLE_BKGD_PIN_XPIN_8
#define ENABLE_RSSI_PWM_XPIN_6

/* rtc0 component */
#define ENABLE_RTC

/* network0 component */
#define ENABLE_XBEE_HANDLE_MODEM_STATUS_FRAMES

/* uart0 component */
#define ENABLE_UART
#define UART_CFG_MODE_2W                1
#define UART_CFG_BAUDRATE               115200
#define UART_CFG_PAR_EN                 UART_CFG_PARITY_DIS
#define UART_CFG_PAR_VAL                UART_CFG_PARITY_ODD
#define UART_CFG_BITS                   UART_CFG_BITS_8
#define UART_CFG_RX_WATERMARK           1
#define UART_CFG_RX_BUF_LEN             32
#define ENABLE_STDIO_PRINTF_SCANF       1

/* timer0 component */
#define ENABLE_TIMER
#define timer0                          TPM1
#define TPM1_OVERFLOW_INTERRUPT
#define timer0_irq                      tpm1ov_irq
#define ENABLE_TPM1

/* irq0 component */
#define ENABLE_GPIO_IRQ_XPIN_7
#define irq0                            XPIN_7
#define irq0_irq                        gpio_irq_handler_xpin_7
#define GPIO_CFG_IRQ_MODE_7             GPIO_CFG_EDGE_IRQ
#define GPIO_IRQ_LEVEL_EDGE_7           GPIO_IRQ_EDGE_FALL
#define GPIO_IRQ_CFG_PULL_7             GPIO_IRQ_CFG_PULL_NONE
#define orPD7                           0
#define andPD7                          ~0
#define orPR7                           0
#define andPR7                          ~shift_xpin_7

/* xbee_config0 component */
#define XBEE_ATCMD_PARAM_ID             "1337"
#define XBEE_ATCMD_PARAM_NI             "water"

/* Used pins macros */
#define XPIN_15_USED
#define XPIN_20_USED
#define XPIN_5_USED
#define XPIN_8_USED
#define XPIN_6_USED
#define XPIN_3_USED
#define XPIN_2_USED
#define XPIN_7_USED


/* Components includes */
#include <custom.h>
#include <system.h>
#include <rtc.h>
#include <pan_init.h>
#include <endpoints.h>
#include <xbee/discovery.h>
#include <xbee/wpan.h>
#include <xbee/atcmd.h>
#include <uart.h>
#include <timer.h>
#include <gpios.h>

#endif /* __XBEE_CONFIG_H_ */
